package com.tggames.frontline.i18n

import com.tggames.frontline.battle.Difficulty
import com.tggames.frontline.battle.EnemyArchetype
import com.tggames.frontline.battle.Tactic
import com.tggames.frontline.catalog.FireMode

object GameI18n {
    fun t(language: GameLanguage, key: String, vararg args: Any): String {
        val values = messages[key] ?: error("Missing translation key: $key")
        var result = values[language.ordinal]
        args.forEachIndexed { index, value -> result = result.replace("{$index}", value.toString()) }
        return result
    }

    fun tactic(language: GameLanguage, tactic: Tactic): String = localized(language, tacticNames.getValue(tactic))
    fun tacticHint(language: GameLanguage, tactic: Tactic): String = localized(language, tacticHints.getValue(tactic))
    fun enemy(language: GameLanguage, enemy: EnemyArchetype): String = localized(language, enemyNames.getValue(enemy))
    fun enemyIntel(language: GameLanguage, enemy: EnemyArchetype): String = localized(language, enemyIntel.getValue(enemy))
    fun difficulty(language: GameLanguage, difficulty: Difficulty): String = localized(language, difficultyNames.getValue(difficulty))
    fun intelLevel(language: GameLanguage, difficulty: Difficulty): String = localized(language, intelLevels.getValue(difficulty))
    fun battlefield(language: GameLanguage, russianName: String): String = localized(language, battlefields[russianName] ?: eight(russianName))
    fun biome(language: GameLanguage, russianName: String): String = localized(language, biomes[russianName] ?: eight(russianName))
    fun fireMode(language: GameLanguage, fireMode: FireMode): String = localized(language, fireModes.getValue(fireMode))

    private fun localized(language: GameLanguage, values: List<String>) = values[language.ordinal]
    private fun eight(value: String) = List(GameLanguage.entries.size) { value }
    private fun v(en: String, ru: String, es: String, pt: String, ar: String, id: String, hi: String, tr: String) =
        listOf(en, ru, es, pt, ar, id, hi, tr)

    private val messages = mapOf(
        "battle_complete" to v("⚔ OPERATION COMPLETE", "⚔ ОПЕРАЦИЯ ЗАВЕРШЕНА", "⚔ OPERACIÓN COMPLETADA", "⚔ OPERAÇÃO CONCLUÍDA", "⚔ اكتملت العملية", "⚔ OPERASI SELESAI", "⚔ अभियान पूरा", "⚔ OPERASYON TAMAMLANDI"),
        "map_mountain_pass" to v("Mountain pass tactical map", "Тактическая карта горного перевала", "Mapa táctico del paso montañoso", "Mapa tático do passo montanhoso", "خريطة تكتيكية للممر الجبلي", "Peta taktis celah gunung", "पर्वतीय दर्रे का सामरिक मानचित्र", "Dağ geçidi taktik haritası"),
        "map_river_valley" to v("River valley tactical map", "Тактическая карта речной долины", "Mapa táctico del valle fluvial", "Mapa tático do vale fluvial", "خريطة تكتيكية لوادي النهر", "Peta taktis lembah sungai", "नदी घाटी का सामरिक मानचित्र", "Nehir vadisi taktik haritası"),
        "map_open_front" to v("Open-front tactical map", "Тактическая карта открытого фронта", "Mapa táctico del frente abierto", "Mapa tático da frente aberta", "خريطة تكتيكية للجبهة المفتوحة", "Peta taktis front terbuka", "खुले मोर्चे का सामरिक मानचित्र", "Açık cephe taktik haritası"),
        "map_legend" to v("A–C entry · 1–3 objectives · △ mountain · ▲ hill · ♣ forest · ≈ water · ≋ marsh · ═ road", "A–C вход · 1–3 объекты · △ гора · ▲ холм · ♣ лес · ≈ вода · ≋ болото · ═ дорога", "A–C entrada · 1–3 objetivos · △ montaña · ▲ colina · ♣ bosque · ≈ agua · ≋ pantano · ═ camino", "A–C entrada · 1–3 objetivos · △ montanha · ▲ colina · ♣ floresta · ≈ água · ≋ pântano · ═ estrada", "A–C مدخل · 1–3 أهداف · △ جبل · ▲ تل · ♣ غابة · ≈ ماء · ≋ مستنقع · ═ طريق", "A–C masuk · 1–3 sasaran · △ gunung · ▲ bukit · ♣ hutan · ≈ air · ≋ rawa · ═ jalan", "A–C प्रवेश · 1–3 लक्ष्य · △ पहाड़ · ▲ पहाड़ी · ♣ जंगल · ≈ पानी · ≋ दलदल · ═ सड़क", "A–C giriş · 1–3 hedef · △ dağ · ▲ tepe · ♣ orman · ≈ su · ≋ bataklık · ═ yol"),
        "map_legend_open" to v("· plain · ∘ desert · ∗ tundra · ∼ coast", "· равнина · ∘ пустыня · ∗ тундра · ∼ побережье", "· llanura · ∘ desierto · ∗ tundra · ∼ costa", "· planície · ∘ deserto · ∗ tundra · ∼ costa", "· سهل · ∘ صحراء · ∗ تندرا · ∼ ساحل", "· dataran · ∘ gurun · ∗ tundra · ∼ pesisir", "· मैदान · ∘ रेगिस्तान · ∗ टुंड्रा · ∼ तट", "· ova · ∘ çöl · ∗ tundra · ∼ kıyı"),
        "entry_south_pass" to v("Southern pass", "Южный перевал", "Paso sur", "Passo sul", "الممر الجنوبي", "Celah selatan", "दक्षिणी दर्रा", "Güney geçidi"),
        "entry_south_road" to v("Southern road", "Южная дорога", "Camino sur", "Estrada sul", "الطريق الجنوبي", "Jalan selatan", "दक्षिणी सड़क", "Güney yolu"),
        "entry_west_road" to v("Western road", "Западная дорога", "Camino occidental", "Estrada oeste", "الطريق الغربي", "Jalan barat", "पश्चिमी सड़क", "Batı yolu"),
        "entry_east_route" to v("Eastern route", "Восточный маршрут", "Ruta oriental", "Rota leste", "المسار الشرقي", "Rute timur", "पूर्वी मार्ग", "Doğu rotası"),
        "entry_north" to v("Northern approach", "Северный подход", "Acceso norte", "Acesso norte", "المدخل الشمالي", "Jalur utara", "उत्तरी मार्ग", "Kuzey yaklaşımı"),
        "objective_signal_tower" to v("Signal tower", "Вышка связи", "Torre de comunicaciones", "Torre de comunicações", "برج الاتصالات", "Menara komunikasi", "संचार टावर", "İletişim kulesi"),
        "objective_central_crossing" to v("Central crossing", "Центральная переправа", "Cruce central", "Travessia central", "المعبر المركزي", "Penyeberangan tengah", "केंद्रीय पारपथ", "Merkez geçişi"),
        "objective_supply_depot" to v("Supply depot", "Склад снабжения", "Depósito de suministros", "Depósito de suprimentos", "مستودع الإمداد", "Depot suplai", "आपूर्ति डिपो", "İkmal deposu"),
        "capture_steps" to v("capture: {0} uninterrupted steps", "захват: {0} непрерывных шага", "captura: {0} pasos continuos", "captura: {0} passos contínuos", "السيطرة: {0} خطوات متواصلة", "rebut: {0} langkah beruntun", "कब्ज़ा: {0} लगातार चरण", "ele geçirme: {0} kesintisiz adım"),
        "choose_entry" to v("Choose where the active group enters the map:", "Выберите точку входа активной группы:", "Elige la entrada del grupo activo:", "Escolha a entrada do grupo ativo:", "اختر نقطة دخول المجموعة النشطة:", "Pilih titik masuk grup aktif:", "सक्रिय समूह का प्रवेश चुनें:", "Aktif grubun girişini seç:"),
        "route" to v("Route", "Маршрут", "Ruta", "Rota", "المسار", "Rute", "मार्ग", "Rota"),
        "choose_objective" to v("Choose the group's first objective. After securing it, surviving units advance to the remaining objectives.", "Выберите первую цель группы. После её захвата уцелевшая техника пойдёт к оставшимся объектам.", "Elige el primer objetivo. Tras capturarlo, las unidades restantes avanzarán a los demás.", "Escolha o primeiro objetivo. Após capturá-lo, as unidades restantes avançam para os demais.", "اختر الهدف الأول. بعد السيطرة عليه تتقدم الوحدات الباقية نحو الأهداف الأخرى.", "Pilih sasaran pertama. Setelah direbut, unit yang tersisa maju ke sasaran lain.", "समूह का पहला लक्ष्य चुनें। कब्ज़े के बाद बची इकाइयाँ अन्य लक्ष्यों की ओर बढ़ेंगी।", "Grubun ilk hedefini seç. Ele geçirildikten sonra kalan birlikler diğer hedeflere ilerler."),
        "choose_tactic_spatial" to v("Choose movement and target-priority doctrine. It gives no hidden power bonus:", "Выберите порядок движения и приоритет целей. Скрытого бонуса к силе нет:", "Elige la doctrina de movimiento y prioridad de objetivos. No otorga bonificación oculta:", "Escolha a doutrina de movimento e prioridade de alvos. Não há bônus oculto:", "اختر عقيدة الحركة وأولوية الأهداف. لا توجد مكافأة قوة مخفية:", "Pilih doktrin gerak dan prioritas target. Tidak ada bonus kekuatan tersembunyi:", "चाल और लक्ष्य-प्राथमिकता सिद्धांत चुनें। कोई छिपा शक्ति बोनस नहीं है:", "Hareket ve hedef önceliği doktrinini seç. Gizli güç bonusu yoktur:"),
        "battle_steps" to v("Battle steps", "Шагов боя", "Pasos de batalla", "Passos da batalha", "خطوات المعركة", "Langkah pertempuran", "युद्ध चरण", "Savaş adımları"),
        "end_reason" to v("Battle ended by", "Причина завершения", "Fin de la batalla", "Fim da batalha", "سبب انتهاء المعركة", "Pertempuran berakhir karena", "युद्ध समाप्ति कारण", "Savaşın bitiş nedeni"),
        "end_all_objectives" to v("all objectives captured", "захвачены все важные объекты", "todos los objetivos capturados", "todos os objetivos capturados", "تمت السيطرة على جميع الأهداف", "semua sasaran direbut", "सभी लक्ष्य कब्ज़े में", "tüm hedefler ele geçirildi"),
        "end_army_destroyed" to v("one army lost all combat-capable units", "одна из армий полностью утратила боеспособность", "un ejército perdió todas sus unidades operativas", "um exército perdeu todas as unidades operacionais", "فقد أحد الجيشين جميع وحداته القتالية", "satu pasukan kehilangan semua unit operasional", "एक सेना की सभी लड़ाकू इकाइयाँ समाप्त", "bir ordu tüm muharip birliklerini kaybetti"),
        "end_army_routed" to v("one army broke and withdrew", "одна из армий была разбита и отступила", "un ejército fue derrotado y se retiró", "um exército foi derrotado e recuou", "انهار أحد الجيشين وانسحب", "satu pasukan terpukul mundur", "एक सेना टूटकर पीछे हटी", "bir ordu bozulup geri çekildi"),
        "units_remaining" to v("Operational units (you : enemy)", "Боеспособная техника (вы : противник)", "Unidades operativas (tú : enemigo)", "Unidades operacionais (você : inimigo)", "الوحدات القتالية (أنت : العدو)", "Unit operasional (Anda : musuh)", "सक्रिय इकाइयाँ (आप : शत्रु)", "Muharip birlikler (sen : düşman)"),
        "objective_control" to v("Important-object control:", "Контроль важных объектов:", "Control de objetivos importantes:", "Controle de objetivos importantes:", "السيطرة على الأهداف المهمة:", "Kontrol sasaran penting:", "महत्वपूर्ण लक्ष्यों का नियंत्रण:", "Önemli hedeflerin kontrolü:"),
        "player_side" to v("Your side", "Ваша сторона", "Tu bando", "Seu lado", "جانبك", "Pihak Anda", "आपकी ओर", "Senin tarafın"),
        "enemy_side" to v("Enemy", "Противник", "Enemigo", "Inimigo", "العدو", "Musuh", "शत्रु", "Düşman"),
        "event_objective_captured" to v("{0} captured {1}", "{0}: захвачен объект «{1}»", "{0} capturó {1}", "{0} capturou {1}", "{0} سيطر على {1}", "{0} merebut {1}", "{0} ने {1} पर कब्ज़ा किया", "{0}, {1} hedefini ele geçirdi"),
        "event_unit_destroyed" to v("{0} destroyed {1}", "{0}: уничтожена техника «{1}»", "{0} destruyó {1}", "{0} destruiu {1}", "{0} دمّر {1}", "{0} menghancurkan {1}", "{0} ने {1} नष्ट किया", "{0}, {1} birliğini imha etti"),
        "event_unit_routed" to v("{0}: {1} withdrew", "{0}: техника «{1}» отступила", "{0}: {1} se retiró", "{0}: {1} recuou", "{0}: انسحب {1}", "{0}: {1} mundur", "{0}: {1} पीछे हटी", "{0}: {1} geri çekildi"),
        "step" to v("Step", "Шаг", "Paso", "Passo", "الخطوة", "Langkah", "चरण", "Adım"),
        "enemy_label" to v("Enemy", "Противник", "Enemigo", "Inimigo", "العدو", "Musuh", "शत्रु", "Düşman"),
        "final_power" to v("Final power", "Итоговая сила", "Fuerza final", "Força final", "القوة النهائية", "Kekuatan akhir", "अंतिम शक्ति", "Nihai güç"),
        "counter_order" to v("Counter-order", "Контрприказ", "Contraorden", "Contraordem", "الأمر المضاد", "Kontra-perintah", "जवाबी आदेश", "Karşı emir"),
        "composition_power" to v("Equipment power", "Сила техники", "Potencia técnica", "Força técnica", "قوة المعدات", "Kekuatan unit", "तकनीकी शक्ति", "Teçhizat gücü"),
        "tactic_fit" to v("Composition fit", "Совместимость состава", "Ajuste de composición", "Adequação da composição", "ملاءمة التشكيل", "Kecocokan formasi", "संरचना अनुकूलता", "Dizilim uyumu"),
        "army" to v("🧰 Army", "🧰 Армия", "🧰 Ejército", "🧰 Exército", "🧰 الجيش", "🧰 Pasukan", "🧰 सेना", "🧰 Ordu"),
        "shop" to v("🏭 Arsenal", "🏭 Арсенал", "🏭 Arsenal", "🏭 Arsenal", "🏭 الترسانة", "🏭 Arsenal", "🏭 शस्त्रागार", "🏭 Cephanelik"),
        "army_title" to v("🧰 COMBAT GROUPS", "🧰 БОЕВЫЕ ГРУППЫ", "🧰 GRUPOS DE COMBATE", "🧰 GRUPOS DE COMBATE", "🧰 مجموعات القتال", "🧰 GRUP TEMPUR", "🧰 युद्ध समूह", "🧰 MUHAREBE GRUPLARI"),
        "cp_limit" to v("Command Point limit", "Лимит Command Points", "Límite de puntos de mando", "Limite de pontos de comando", "حد نقاط القيادة", "Batas Poin Komando", "कमांड पॉइंट सीमा", "Komuta Puanı sınırı"),
        "active_group" to v("Active group", "Активная группа", "Grupo activo", "Grupo ativo", "المجموعة النشطة", "Grup aktif", "सक्रिय समूह", "Aktif grup"),
        "army_empty" to v("The active group is empty. Add at least one unit.", "Активная группа пуста. Добавьте хотя бы одну машину.", "El grupo activo está vacío. Añade una unidad.", "O grupo ativo está vazio. Adicione uma unidade.", "المجموعة النشطة فارغة. أضف وحدة واحدة.", "Grup aktif kosong. Tambahkan satu unit.", "सक्रिय समूह खाली है। एक यूनिट जोड़ें।", "Aktif grup boş. En az bir birlik ekle."),
        "army_hint" to v("Choose a preset, then add or remove owned units. A battle uses this exact composition.", "Выберите пресет, затем добавляйте или убирайте свою технику. В бой уйдёт именно этот состав.", "Elige un preset y añade o quita unidades. La batalla usará esa composición.", "Escolha um preset e adicione ou remova unidades. A batalha usará essa composição.", "اختر إعدادًا ثم أضف أو أزل وحداتك. ستستخدم المعركة هذا التشكيل.", "Pilih preset lalu tambah atau hapus unit. Pertempuran memakai susunan ini.", "प्रीसेट चुनें, फिर यूनिट जोड़ें या हटाएँ। युद्ध इसी संरचना से होगा।", "Bir hazır grup seç, birlik ekle veya çıkar. Savaş bu dizilimi kullanır."),
        "shop_title" to v("🏭 EQUIPMENT ARSENAL", "🏭 АРСЕНАЛ ТЕХНИКИ", "🏭 ARSENAL DE EQUIPO", "🏭 ARSENAL DE EQUIPAMENTO", "🏭 ترسانة المعدات", "🏭 ARSENAL UNIT", "🏭 उपकरण शस्त्रागार", "🏭 TEÇHİZAT CEPHANELİĞİ"),
        "shop_hint" to v("Buy with Credits or craft more efficiently with Credits and Materials.", "Покупайте за Credits или производите выгоднее из Credits и Materials.", "Compra con Credits o fabrica con Credits y Materials.", "Compre com Credits ou fabrique com Credits e Materials.", "اشترِ بالاعتمادات أو اصنع بكفاءة باستخدام الاعتمادات والمواد.", "Beli dengan Credits atau rakit lebih hemat memakai Credits dan Materials.", "Credits से खरीदें या Credits और Materials से कम लागत में बनाएँ।", "Credits ile satın al veya Credits ve Materials ile daha verimli üret."),
        "unit_stats" to v("Attack · armor · mobility · recon · support", "Атака · броня · мобильность · разведка · поддержка", "Ataque · blindaje · movilidad · reconocimiento · apoyo", "Ataque · blindagem · mobilidade · reconhecimento · suporte", "هجوم · درع · حركة · استطلاع · دعم", "Serang · zirah · mobilitas · pengintaian · dukungan", "आक्रमण · कवच · गतिशीलता · टोही · समर्थन", "Saldırı · zırh · hareket · keşif · destek"),
        "spatial_stats" to v("Map movement · weapon range · sight", "Движение по карте · дальность оружия · обзор", "Movimiento · alcance · visión", "Movimento · alcance · visão", "الحركة · مدى السلاح · الرؤية", "Gerak · jangkauan · penglihatan", "चाल · हथियार दूरी · दृष्टि", "Hareket · silah menzili · görüş"),
        "buy" to v("Buy", "Купить", "Comprar", "Comprar", "شراء", "Beli", "खरीदें", "Satın al"),
        "craft" to v("Craft", "Произвести", "Fabricar", "Produzir", "تصنيع", "Rakit", "निर्माण", "Üret"),
        "upgrade_title" to v("⬆️ EQUIPMENT UPGRADES", "⬆️ ПРОКАЧКА ТЕХНИКИ", "⬆️ MEJORAS DE EQUIPO", "⬆️ MELHORIAS DE EQUIPAMENTO", "⬆️ ترقيات المعدات", "⬆️ PENINGKATAN UNIT", "⬆️ उपकरण उन्नयन", "⬆️ TEÇHİZAT YÜKSELTMELERİ"),
        "upgrade_growth" to v("Each level adds 12% to all base stats; maximum level is 5.", "Каждый уровень даёт +12% ко всем базовым характеристикам; максимум — 5.", "Cada nivel añade 12% a todas las estadísticas; máximo 5.", "Cada nível adiciona 12% aos atributos; máximo 5.", "يضيف كل مستوى 12٪ إلى الخصائص الأساسية؛ الحد الأقصى 5.", "Tiap level menambah 12% statistik dasar; maksimum 5.", "हर स्तर सभी मूल आँकड़ों में 12% जोड़ता है; अधिकतम 5।", "Her seviye temel değerlere %12 ekler; en fazla 5."),
        "equipment_success" to v("Equipment updated: {0}, level {1}.", "Техника обновлена: {0}, уровень {1}.", "Equipo actualizado: {0}, nivel {1}.", "Equipamento atualizado: {0}, nível {1}.", "تم تحديث المعدات: {0}، المستوى {1}.", "Unit diperbarui: {0}, level {1}.", "उपकरण अपडेट: {0}, स्तर {1}।", "Teçhizat güncellendi: {0}, seviye {1}."),
        "equipment_locked" to v("Unlocks at commander level {0}.", "Откроется на уровне командира {0}.", "Se desbloquea en nivel de comandante {0}.", "Desbloqueia no nível de comandante {0}.", "يُفتح عند مستوى القائد {0}.", "Terbuka di level komandan {0}.", "कमांडर स्तर {0} पर खुलेगा।", "Komutan seviyesi {0}'da açılır."),
        "insufficient_resources" to v("Not enough Credits or Materials.", "Недостаточно Credits или Materials.", "No hay suficientes Credits o Materials.", "Credits ou Materials insuficientes.", "لا توجد اعتمادات أو مواد كافية.", "Credits atau Materials tidak cukup.", "Credits या Materials पर्याप्त नहीं हैं।", "Yeterli Credits veya Materials yok."),
        "max_level" to v("This unit is already at maximum level.", "Эта техника уже максимального уровня.", "Esta unidad ya está al nivel máximo.", "Esta unidade já está no nível máximo.", "هذه الوحدة في المستوى الأقصى.", "Unit ini sudah level maksimum.", "यह यूनिट अधिकतम स्तर पर है।", "Bu birlik zaten en yüksek seviyede."),
        "group_full" to v("The Command Point limit would be exceeded.", "Будет превышен лимит Command Points.", "Se superaría el límite de puntos de mando.", "O limite de pontos de comando seria excedido.", "سيتم تجاوز حد نقاط القيادة.", "Batas Poin Komando akan terlampaui.", "कमांड पॉइंट सीमा पार हो जाएगी।", "Komuta Puanı sınırı aşılır."),
        "last_unit" to v("A combat group must keep at least one unit.", "В боевой группе должна остаться хотя бы одна машина.", "El grupo debe conservar al menos una unidad.", "O grupo deve manter ao menos uma unidade.", "يجب أن تبقى وحدة واحدة على الأقل.", "Grup harus memiliki setidaknya satu unit.", "युद्ध समूह में कम से कम एक यूनिट रहनी चाहिए।", "Muharebe grubunda en az bir birlik kalmalı."),
        "victory" to v("🏆 VICTORY", "🏆 ПОБЕДА", "🏆 VICTORIA", "🏆 VITÓRIA", "🏆 انتصار", "🏆 MENANG", "🏆 विजय", "🏆 ZAFER"),
        "withdrawal" to v("↩️ ORDERLY WITHDRAWAL", "↩️ ОРГАНИЗОВАННОЕ ОТСТУПЛЕНИЕ", "↩️ RETIRADA ORDENADA", "↩️ RETIRADA ORGANIZADA", "↩️ انسحاب منظم", "↩️ MUNDUR TERATUR", "↩️ व्यवस्थित वापसी", "↩️ DÜZENLİ ÇEKİLME"),
        "round" to v("Round", "Раунд", "Ronda", "Rodada", "الجولة", "Ronde", "दौर", "Tur"),
        "likely" to v("likely", "вероятно", "probable", "provável", "محتمل", "kemungkinan", "संभावित", "muhtemel"),
        "unknown_composition" to v("enemy composition unknown", "состав противника неизвестен", "composición enemiga desconocida", "composição inimiga desconhecida", "تشكيل العدو غير معروف", "komposisi musuh tidak diketahui", "शत्रु संरचना अज्ञात", "düşman bileşimi bilinmiyor"),
        "objective_secured" to v("Objective secured", "Цель операции взята под контроль", "Objetivo asegurado", "Objetivo controlado", "تم تأمين الهدف", "Sasaran diamankan", "लक्ष्य सुरक्षित", "Hedef ele geçirildi"),
        "unit_withdrew" to v("Unit withdrew in good order", "Группа организованно отошла с рубежа", "La unidad se retiró ordenadamente", "A unidade recuou em ordem", "انسحبت الوحدة بنظام", "Unit mundur dengan teratur", "इकाई व्यवस्थित पीछे हटी", "Birim düzenli çekildi"),
        "initiative_seized" to v("initiative seized", "захвачена инициатива", "iniciativa tomada", "iniciativa conquistada", "تم انتزاع المبادرة", "inisiatif direbut", "पहल हासिल", "inisiyatif ele geçirildi"),
        "enemy_suppressed" to v("Enemy position suppressed", "Ключевая позиция противника подавлена", "Posición enemiga neutralizada", "Posição inimiga suprimida", "تم إخماد موقع العدو", "Posisi musuh ditekan", "शत्रु स्थिति दबाई गई", "Düşman mevzisi bastırıldı"),
        "advance_slowed" to v("Advance slowed by resistance", "Продвижение замедлено сопротивлением", "Avance frenado por la resistencia", "Avanço reduzido pela resistência", "أبطأت المقاومة التقدم", "Gerak maju diperlambat perlawanan", "प्रतिरोध से बढ़त धीमी", "İlerleyiş direnişle yavaşladı"),
        "new_level" to v("New commander level", "Новый уровень командира", "Nuevo nivel de comandante", "Novo nível de comandante", "مستوى قائد جديد", "Level komandan baru", "नया कमांडर स्तर", "Yeni komutan seviyesi"),
        "unknown" to v("Unknown command.", "Неизвестная команда.", "Comando desconocido.", "Comando desconhecido.", "أمر غير معروف.", "Perintah tidak dikenal.", "अज्ञात कमांड।", "Bilinmeyen komut."),
        "welcome" to v("Welcome to Frontline Nations, {0}!", "Добро пожаловать в Frontline Nations, {0}!", "¡Bienvenido a Frontline Nations, {0}!", "Bem-vindo ao Frontline Nations, {0}!", "مرحبًا بك في Frontline Nations، {0}!", "Selamat datang di Frontline Nations, {0}!", "Frontline Nations में आपका स्वागत है, {0}!", "Frontline Nations'a hoş geldin, {0}!"),
        "country_neutral" to v("Choose your country or territory. Names and flags are neutral game identifiers.", "Выберите страну или территорию. Названия и флаги — нейтральные игровые идентификаторы.", "Elige tu país o territorio. Los nombres y banderas son identificadores neutrales del juego.", "Escolha seu país ou território. Nomes e bandeiras são identificadores neutros do jogo.", "اختر بلدك أو إقليمك. الأسماء والأعلام معرّفات محايدة داخل اللعبة.", "Pilih negara atau wilayah. Nama dan bendera adalah identitas netral dalam gim.", "अपना देश या क्षेत्र चुनें। नाम और झंडे केवल तटस्थ गेम पहचान हैं।", "Ülkeni veya bölgeni seç. Adlar ve bayraklar tarafsız oyun kimlikleridir."),
        "welcome_back" to v("Welcome back, {0}!", "С возвращением, {0}!", "¡Bienvenido de nuevo, {0}!", "Bem-vindo de volta, {0}!", "مرحبًا بعودتك، {0}!", "Selamat datang kembali, {0}!", "वापसी पर स्वागत है, {0}!", "Tekrar hoş geldin, {0}!"),
        "choose_country" to v("Choose a country or territory first:", "Сначала выберите страну или территорию:", "Primero elige un país o territorio:", "Primeiro escolha um país ou território:", "اختر بلدًا أو إقليمًا أولًا:", "Pilih negara atau wilayah terlebih dahulu:", "पहले देश या क्षेत्र चुनें:", "Önce bir ülke veya bölge seç:"),
        "language_title" to v("🌐 LANGUAGE", "🌐 ЯЗЫК", "🌐 IDIOMA", "🌐 IDIOMA", "🌐 اللغة", "🌐 BAHASA", "🌐 भाषा", "🌐 DİL"),
        "language_choose" to v("Current: {0}\nChoose a language:", "Текущий: {0}\nВыберите язык:", "Actual: {0}\nElige un idioma:", "Atual: {0}\nEscolha um idioma:", "الحالي: {0}\nاختر اللغة:", "Saat ini: {0}\nPilih bahasa:", "वर्तमान: {0}\nभाषा चुनें:", "Mevcut: {0}\nBir dil seç:"),
        "language_changed" to v("Language changed to {0}.", "Язык изменён на {0}.", "Idioma cambiado a {0}.", "Idioma alterado para {0}.", "تم تغيير اللغة إلى {0}.", "Bahasa diubah ke {0}.", "भाषा {0} में बदल दी गई।", "Dil {0} olarak değiştirildi."),
        "nickname_prompt" to v("Current nickname: {0}\nSend a new one after the command, for example: /nickname Commander", "Текущий ник: {0}\nУкажите новый после команды, например: /nickname Командир", "Apodo actual: {0}\nEscribe uno nuevo, por ejemplo: /nickname Comandante", "Apelido atual: {0}\nEnvie um novo, por exemplo: /nickname Comandante", "الاسم الحالي: {0}\nأرسل اسمًا جديدًا، مثل: /nickname قائد", "Nama saat ini: {0}\nKirim nama baru, contoh: /nickname Komandan", "वर्तमान नाम: {0}\nनया नाम भेजें, जैसे: /nickname कमांडर", "Mevcut ad: {0}\nYeni adı gönder, örnek: /nickname Komutan"),
        "not_set" to v("not set", "не установлен", "no definido", "não definido", "غير محدد", "belum diatur", "सेट नहीं", "ayarlanmadı"),
        "nickname_invalid" to v("Nickname must contain a letter or number and be at most 30 characters. Unsafe control characters are removed and profanity is masked.", "Ник должен содержать букву или цифру и быть не длиннее 30 символов. Опасные управляющие символы удаляются, мат маскируется.", "El apodo debe contener una letra o número y tener hasta 30 caracteres. Se eliminan controles peligrosos y se ocultan insultos.", "O apelido deve conter letra ou número e ter até 30 caracteres. Controles perigosos são removidos e palavrões mascarados.", "يجب أن يحتوي الاسم على حرف أو رقم وألا يتجاوز 30 حرفًا. تُحذف رموز التحكم وتُحجب الألفاظ المسيئة.", "Nama harus memiliki huruf atau angka dan maksimal 30 karakter. Karakter kontrol dihapus dan kata kasar disamarkan.", "नाम में अक्षर या अंक होना चाहिए और अधिकतम 30 वर्ण हो सकते हैं। नियंत्रण चिह्न हटते हैं और अपशब्द छिपते हैं।", "Ad en fazla 30 karakter olmalı ve harf ya da rakam içermelidir. Kontrol karakterleri silinir, küfürler maskelenir."),
        "nickname_same" to v("This nickname is already set.", "Этот ник уже установлен.", "Ese apodo ya está definido.", "Esse apelido já está definido.", "هذا الاسم مستخدم بالفعل.", "Nama itu sudah digunakan.", "यह नाम पहले से सेट है।", "Bu ad zaten ayarlı."),
        "nickname_confirm" to v("Change your nickname from “{0}” to “{1}”?", "Изменить ник с «{0}» на «{1}»?", "¿Cambiar el apodo de «{0}» a «{1}»?", "Alterar o apelido de “{0}” para “{1}”?", "تغيير الاسم من «{0}» إلى «{1}»؟", "Ubah nama dari “{0}” menjadi “{1}”?", "नाम “{0}” से “{1}” करें?", "Ad “{0}” iken “{1}” olarak değişsin mi?"),
        "nickname_changed" to v("Nickname changed to “{0}”.", "Ник изменён на «{0}».", "Apodo cambiado a «{0}».", "Apelido alterado para “{0}”.", "تم تغيير الاسم إلى «{0}».", "Nama diubah menjadi “{0}”.", "नाम “{0}” कर दिया गया।", "Ad “{0}” olarak değiştirildi."),
        "nickname_cancelled" to v("Nickname change cancelled.", "Смена ника отменена.", "Cambio de apodo cancelado.", "Alteração de apelido cancelada.", "تم إلغاء تغيير الاسم.", "Perubahan nama dibatalkan.", "नाम बदलना रद्द हुआ।", "Ad değişikliği iptal edildi."),
        "yes" to v("✅ Yes", "✅ Да", "✅ Sí", "✅ Sim", "✅ نعم", "✅ Ya", "✅ हाँ", "✅ Evet"),
        "no" to v("❌ No", "❌ Нет", "❌ No", "❌ Não", "❌ لا", "❌ Tidak", "❌ नहीं", "❌ Hayır"),
        "country_title" to v("🌍 COUNTRY OR TERRITORY", "🌍 СТРАНА ИЛИ ТЕРРИТОРИЯ", "🌍 PAÍS O TERRITORIO", "🌍 PAÍS OU TERRITÓRIO", "🌍 البلد أو الإقليم", "🌍 NEGARA ATAU WILAYAH", "🌍 देश या क्षेत्र", "🌍 ÜLKE VEYA BÖLGE"),
        "country_recommended" to v("Suggested from your Telegram language:", "Предложения на основе языка Telegram:", "Sugerencias según tu idioma de Telegram:", "Sugestões com base no idioma do Telegram:", "اقتراحات بناءً على لغة تيليجرام:", "Saran berdasarkan bahasa Telegram:", "Telegram भाषा के आधार पर सुझाव:", "Telegram diline göre öneriler:"),
        "country_search" to v("Search all 250 options: /country name or code", "Поиск по 250 вариантам: /country название или код", "Busca entre 250 opciones: /country nombre o código", "Busque entre 250 opções: /country nome ou código", "ابحث في 250 خيارًا: /country الاسم أو الرمز", "Cari dari 250 pilihan: /country nama atau kode", "250 विकल्प खोजें: /country नाम या कोड", "250 seçenek içinde ara: /country ad veya kod"),
        "country_results" to v("Search results for “{0}”:", "Результаты поиска «{0}»:", "Resultados para «{0}»:", "Resultados para “{0}”:", "نتائج البحث عن «{0}»:", "Hasil pencarian “{0}”:", "“{0}” के खोज परिणाम:", "“{0}” arama sonuçları:"),
        "country_none" to v("Nothing found. Try a local name, English name, or two-letter code.", "Ничего не найдено. Попробуйте местное/английское название или двухбуквенный код.", "No se encontró nada. Prueba el nombre local, inglés o el código de dos letras.", "Nada encontrado. Tente o nome local, em inglês ou o código de duas letras.", "لم يتم العثور على نتائج. جرّب الاسم المحلي أو الإنجليزي أو الرمز الثنائي.", "Tidak ditemukan. Coba nama lokal, Inggris, atau kode dua huruf.", "कुछ नहीं मिला। स्थानीय/अंग्रेज़ी नाम या दो-अक्षर कोड आज़माएँ।", "Sonuç bulunamadı. Yerel/İngilizce ad veya iki harfli kod deneyin."),
        "country_page" to v("All options · page {0}/{1}", "Все варианты · страница {0}/{1}", "Todas las opciones · página {0}/{1}", "Todas as opções · página {0}/{1}", "كل الخيارات · الصفحة {0}/{1}", "Semua pilihan · halaman {0}/{1}", "सभी विकल्प · पृष्ठ {0}/{1}", "Tüm seçenekler · sayfa {0}/{1}"),
        "country_selected" to v("Country selected: {0}", "Страна выбрана: {0}", "País elegido: {0}", "País escolhido: {0}", "تم اختيار البلد: {0}", "Negara dipilih: {0}", "देश चुना गया: {0}", "Ülke seçildi: {0}"),
        "country_locked" to v("Your current alliance is {0}. Alliance changes will be added with seasonal rules; they are not available yet.", "Ваш текущий альянс — {0}. Смена появится вместе с сезонными правилами и пока недоступна.", "Tu alianza actual es {0}. Los cambios llegarán con las reglas de temporada y aún no están disponibles.", "Sua aliança atual é {0}. A troca chegará com as regras sazonais e ainda não está disponível.", "تحالفك الحالي هو {0}. سيُتاح التغيير مع قواعد الموسم وليس متاحًا الآن.", "Aliansi saat ini {0}. Pergantian akan hadir bersama aturan musim dan belum tersedia.", "आपका मौजूदा गठबंधन {0} है। बदलाव सीज़न नियमों के साथ आएगा और अभी उपलब्ध नहीं है।", "Mevcut ittifakın {0}. Değişiklik sezon kurallarıyla gelecek ve henüz kullanılamıyor."),
        "all_options" to v("📚 All options", "📚 Все варианты", "📚 Todas", "📚 Todas", "📚 كل الخيارات", "📚 Semua pilihan", "📚 सभी विकल्प", "📚 Tüm seçenekler"),
        "previous" to v("⬅️ Previous", "⬅️ Назад", "⬅️ Anterior", "⬅️ Anterior", "⬅️ السابق", "⬅️ Sebelumnya", "⬅️ पिछला", "⬅️ Önceki"),
        "next" to v("Next ➡️", "Далее ➡️", "Siguiente ➡️", "Próxima ➡️", "التالي ➡️", "Berikutnya ➡️", "अगला ➡️", "Sonraki ➡️"),
        "battle" to v("⚔️ Battle", "⚔️ В бой", "⚔️ Batalla", "⚔️ Batalha", "⚔️ معركة", "⚔️ Bertempur", "⚔️ युद्ध", "⚔️ Savaş"),
        "profile" to v("🪖 Profile", "🪖 Профиль", "🪖 Perfil", "🪖 Perfil", "🪖 الملف", "🪖 Profil", "🪖 प्रोफ़ाइल", "🪖 Profil"),
        "front" to v("🌍 Front", "🌍 Фронт", "🌍 Frente", "🌍 Frente", "🌍 الجبهة", "🌍 Front", "🌍 मोर्चा", "🌍 Cephe"),
        "settings" to v("⚙️ Settings", "⚙️ Настройки", "⚙️ Ajustes", "⚙️ Ajustes", "⚙️ الإعدادات", "⚙️ Pengaturan", "⚙️ सेटिंग", "⚙️ Ayarlar"),
        "settings_text" to v("Settings: /language · /nickname · /country\nGame: /army · /shop · /upgrade", "Настройки: /language · /nickname · /country\nИгра: /army · /shop · /upgrade", "Ajustes: /language · /nickname · /country\nJuego: /army · /shop · /upgrade", "Ajustes: /language · /nickname · /country\nJogo: /army · /shop · /upgrade", "الإعدادات: /language · /nickname · /country\nاللعبة: /army · /shop · /upgrade", "Pengaturan: /language · /nickname · /country\nGim: /army · /shop · /upgrade", "सेटिंग: /language · /nickname · /country\nगेम: /army · /shop · /upgrade", "Ayarlar: /language · /nickname · /country\nOyun: /army · /shop · /upgrade"),
        "no_orders" to v("No Combat Orders left. Refill is at 00:00 game time.", "Боевые приказы закончились. Пополнение — в 00:00 по игровому времени.", "No quedan órdenes. Se reponen a las 00:00 del juego.", "Sem ordens. Reposição às 00:00 do jogo.", "نفدت أوامر القتال. التجديد الساعة 00:00 بتوقيت اللعبة.", "Perintah tempur habis. Diisi ulang pukul 00:00 waktu gim.", "युद्ध आदेश खत्म। गेम समय 00:00 पर फिर मिलेंगे।", "Savaş Emri kalmadı. Oyun saatiyle 00:00'da yenilenir."),
        "operations" to v("🗺 AVAILABLE OPERATIONS", "🗺 ДОСТУПНЫЕ ОПЕРАЦИИ", "🗺 OPERACIONES DISPONIBLES", "🗺 OPERAÇÕES DISPONÍVEIS", "🗺 العمليات المتاحة", "🗺 OPERASI TERSEDIA", "🗺 उपलब्ध अभियान", "🗺 MEVCUT OPERASYONLAR"),
        "terrain" to v("Terrain", "Местность", "Terreno", "Terreno", "التضاريس", "Medan", "भूभाग", "Arazi"),
        "risk" to v("Risk", "Риск", "Riesgo", "Risco", "المخاطر", "Risiko", "जोखिम", "Risk"),
        "reward" to v("Reward", "Награда", "Recompensa", "Recompensa", "المكافأة", "Hadiah", "इनाम", "Ödül"),
        "intel" to v("Intel", "Разведданные", "Inteligencia", "Inteligência", "الاستخبارات", "Intel", "खुफिया", "İstihbarat"),
        "orders_choose" to v("Orders: {0}/5. Choose an operation; it is spent only after selecting a tactic.", "Приказов: {0}/5. Выберите операцию — приказ спишется после выбора тактики.", "Órdenes: {0}/5. Elige operación; se gasta al elegir táctica.", "Ordens: {0}/5. Escolha a operação; será gasta após escolher a tática.", "الأوامر: {0}/5. اختر عملية؛ يُستهلك الأمر بعد اختيار التكتيك.", "Perintah: {0}/5. Pilih operasi; terpakai setelah memilih taktik.", "आदेश: {0}/5। अभियान चुनें; रणनीति चुनने के बाद आदेश खर्च होगा।", "Emir: {0}/5. Operasyon seç; taktik seçilince harcanır."),
        "choose_tactic" to v("Choose a tactic. Counter-orders and terrain can outweigh raw power:", "Выберите тактику. Контрприказ и местность могут перевесить разницу в силе:", "Elige una táctica. Las contraórdenes y el terreno pueden superar la fuerza bruta:", "Escolha uma tática. Contraordens e terreno podem superar a força bruta:", "اختر تكتيكًا. قد تتغلب الأوامر المضادة والتضاريس على القوة الخام:", "Pilih taktik. Kontra-perintah dan medan dapat mengalahkan kekuatan mentah:", "रणनीति चुनें। जवाबी आदेश और भूभाग कच्ची शक्ति पर भारी पड़ सकते हैं:", "Taktik seç. Karşı emir ve arazi ham gücü aşabilir:"),
        "other_operations" to v("↩️ Other operations", "↩️ Другие операции", "↩️ Otras operaciones", "↩️ Outras operações", "↩️ عمليات أخرى", "↩️ Operasi lain", "↩️ अन्य अभियान", "↩️ Diğer operasyonlar"),
        "stale" to v("This offer expired or the order was already used. Refresh the operation list.", "Предложение устарело или приказ уже использован. Обновите список операций.", "La oferta caducó o la orden ya se usó. Actualiza la lista.", "A oferta expirou ou a ordem já foi usada. Atualize a lista.", "انتهى العرض أو استُخدم الأمر. حدّث قائمة العمليات.", "Penawaran kedaluwarsa atau perintah sudah dipakai. Muat ulang daftar.", "ऑफ़र समाप्त या आदेश उपयोग हो चुका। सूची रीफ़्रेश करें।", "Teklif süresi doldu veya emir kullanıldı. Listeyi yenile."),
        "contribute_usage" to v("Enter 10–10000 Credits: /contribute 100", "Укажите от 10 до 10000 Credits: /contribute 100", "Indica 10–10000 Credits: /contribute 100", "Informe 10–10000 Credits: /contribute 100", "أدخل 10–10000 Credits: /contribute 100", "Masukkan 10–10000 Credits: /contribute 100", "10–10000 Credits दर्ज करें: /contribute 100", "10–10000 Credits gir: /contribute 100"),
        "commander" to v("COMMANDER", "КОМАНДИР", "COMANDANTE", "COMANDANTE", "القائد", "KOMANDAN", "कमांडर", "KOMUTAN"),
        "alliance" to v("Alliance", "Альянс", "Alianza", "Aliança", "التحالف", "Aliansi", "गठबंधन", "İttifak"),
        "not_selected" to v("not selected", "не выбран", "sin elegir", "não escolhido", "غير محدد", "belum dipilih", "नहीं चुना", "seçilmedi"),
        "level" to v("Level", "Уровень", "Nivel", "Nível", "المستوى", "Level", "स्तर", "Seviye"),
        "victories" to v("Wins", "Победы", "Victorias", "Vitórias", "الانتصارات", "Menang", "जीत", "Galibiyet"),
        "streak" to v("Streak", "Серия", "Racha", "Sequência", "السلسلة", "Rentetan", "सिलसिला", "Seri"),
        "record" to v("record", "рекорд", "récord", "recorde", "الرقم القياسي", "rekor", "रिकॉर्ड", "rekor"),
        "combat_orders" to v("Combat Orders", "Боевые приказы", "Órdenes de combate", "Ordens de combate", "أوامر القتال", "Perintah Tempur", "युद्ध आदेश", "Savaş Emirleri"),
        "help" to v("Frontline Nations commands:\n/start — start and country choice\n/battle — daily operation\n/profile — progress and resources\n/front — weekly battle\n/contribute 100 — support the front\n/country [name] — country catalog/search\n/language — change language\n/nickname [name] — change nickname\n/help — this help", "Команды Frontline Nations:\n/start — старт и выбор страны\n/battle — ежедневная операция\n/profile — прогресс и ресурсы\n/front — недельная битва\n/contribute 100 — поддержать фронт\n/country [название] — каталог/поиск страны\n/language — сменить язык\n/nickname [имя] — сменить ник\n/help — эта справка", "Comandos:\n/start — inicio y país\n/battle — operación diaria\n/profile — progreso\n/front — batalla semanal\n/contribute 100 — apoyar el frente\n/country [nombre] — catálogo/búsqueda\n/language — idioma\n/nickname [nombre] — apodo\n/help — ayuda", "Comandos:\n/start — início e país\n/battle — operação diária\n/profile — progresso\n/front — batalha semanal\n/contribute 100 — apoiar a frente\n/country [nome] — catálogo/busca\n/language — idioma\n/nickname [nome] — apelido\n/help — ajuda", "الأوامر:\n/start — البدء واختيار البلد\n/battle — عملية يومية\n/profile — التقدم\n/front — المعركة الأسبوعية\n/contribute 100 — دعم الجبهة\n/country [اسم] — البحث عن بلد\n/language — اللغة\n/nickname [اسم] — الاسم\n/help — المساعدة", "Perintah:\n/start — mulai dan pilih negara\n/battle — operasi harian\n/profile — progres\n/front — pertempuran mingguan\n/contribute 100 — dukung front\n/country [nama] — katalog/cari\n/language — bahasa\n/nickname [nama] — nama\n/help — bantuan", "कमांड:\n/start — शुरू और देश चयन\n/battle — दैनिक अभियान\n/profile — प्रगति\n/front — साप्ताहिक युद्ध\n/contribute 100 — मोर्चे का समर्थन\n/country [नाम] — देश खोज\n/language — भाषा\n/nickname [नाम] — नाम\n/help — सहायता", "Komutlar:\n/start — başlangıç ve ülke\n/battle — günlük operasyon\n/profile — ilerleme\n/front — haftalık savaş\n/contribute 100 — cepheyi destekle\n/country [ad] — katalog/arama\n/language — dil\n/nickname [ad] — kullanıcı adı\n/help — yardım"),
    )

    private val tacticNames = mapOf(
        Tactic.ASSAULT to v("Assault", "Штурм", "Asalto", "Assalto", "هجوم", "Serbu", "आक्रमण", "Taarruz"),
        Tactic.DEFENSE to v("Defense", "Оборона", "Defensa", "Defesa", "دفاع", "Pertahanan", "रक्षा", "Savunma"),
        Tactic.AMBUSH to v("Ambush", "Засада", "Emboscada", "Emboscada", "كمين", "Penyergapan", "घात", "Pusu"),
        Tactic.MANEUVER to v("Maneuver", "Манёвр", "Maniobra", "Manobra", "مناورة", "Manuver", "चाल", "Manevra"),
        Tactic.RECON to v("Recon in force", "Разведка боем", "Reconocimiento", "Reconhecimento", "استطلاع قتالي", "Pengintaian tempur", "युद्ध टोही", "Muharebe keşfi"),
    )
    private val tacticHints = Tactic.entries.associateWith { tactic ->
        when (tactic) {
            Tactic.ASSAULT -> v("advance directly and finish damaged targets", "идти прямо к цели и добивать повреждённые цели", "avanzar directo y rematar objetivos dañados", "avançar direto e finalizar alvos danificados", "تقدم مباشر وإنهاء الأهداف المتضررة", "maju langsung dan habisi target rusak", "सीधे बढ़ें और क्षतिग्रस्त लक्ष्यों को खत्म करें", "doğrudan ilerle ve hasarlı hedefleri bitir")
            Tactic.DEFENSE -> v("hold controlled objectives and engage the nearest threat", "удерживать объекты и атаковать ближайшую угрозу", "mantener objetivos y atacar la amenaza más cercana", "manter objetivos e atacar a ameaça mais próxima", "الثبات على الأهداف وضرب أقرب تهديد", "pertahankan sasaran dan serang ancaman terdekat", "लक्ष्यों को थामें और निकटतम खतरे पर हमला करें", "hedefleri tut ve en yakın tehdide saldır")
            Tactic.AMBUSH -> v("prefer covered routes and high-value targets", "выбирать укрытые маршруты и наиболее опасные цели", "preferir rutas cubiertas y objetivos valiosos", "preferir rotas protegidas e alvos valiosos", "تفضيل المسارات المحمية والأهداف عالية القيمة", "pilih rute terlindung dan target bernilai tinggi", "आवृत मार्ग और महत्वपूर्ण लक्ष्य चुनें", "örtülü rotaları ve değerli hedefleri seç")
            Tactic.MANEUVER -> v("use fast terrain and hunt artillery or air defense", "использовать быстрые маршруты и охотиться за артиллерией или ПВО", "usar terreno rápido y cazar artillería o defensa aérea", "usar terreno rápido e caçar artilharia ou defesa aérea", "استخدام المسارات السريعة ومطاردة المدفعية أو الدفاع الجوي", "gunakan jalur cepat dan buru artileri atau pertahanan udara", "तेज़ मार्ग लें और तोपखाने या वायु रक्षा का शिकार करें", "hızlı rotaları kullanıp topçu veya hava savunmasını avla")
            Tactic.RECON -> v("send scouts first and disrupt enemy reconnaissance", "выдвигать разведку первой и подавлять разведку противника", "enviar exploradores primero e interrumpir el reconocimiento enemigo", "enviar reconhecimento primeiro e neutralizar batedores inimigos", "إرسال الاستطلاع أولاً وتعطيل استطلاع العدو", "kirim pengintai lebih dulu dan ganggu pengintaian musuh", "स्काउट पहले भेजें और शत्रु टोही बाधित करें", "keşfi önden gönder ve düşman keşfini boz")
        }
    }
    private val enemyNames = mapOf(
        EnemyArchetype.ARMOR to v("armored group", "бронетанковая группа", "grupo blindado", "grupo blindado", "مجموعة مدرعة", "grup lapis baja", "बख़्तरबंद समूह", "zırhlı grup"),
        EnemyArchetype.ARTILLERY to v("artillery group", "артиллерийская группа", "grupo de artillería", "grupo de artilharia", "مجموعة مدفعية", "grup artileri", "तोपखाना समूह", "topçu grubu"),
        EnemyArchetype.FORTIFIED to v("fortified group", "укреплённая группа", "grupo fortificado", "grupo fortificado", "مجموعة محصنة", "grup berbenteng", "किलेबंद समूह", "tahkim edilmiş grup"),
        EnemyArchetype.AMBUSH to v("concealed group", "скрытная группа", "grupo oculto", "grupo oculto", "مجموعة متخفية", "grup tersembunyi", "छिपा समूह", "gizli grup"),
        EnemyArchetype.MOBILE to v("mobile group", "мобильная группа", "grupo móvil", "grupo móvel", "مجموعة متحركة", "grup bergerak", "गतिशील समूह", "hareketli grup"),
        EnemyArchetype.AIR to v("air strike group", "авиационная группа", "grupo aéreo", "grupo aéreo", "مجموعة جوية", "grup udara", "वायु समूह", "hava grubu"),
        EnemyArchetype.AIR_DEFENSE to v("air-defense group", "группа ПВО", "grupo antiaéreo", "grupo antiaéreo", "مجموعة دفاع جوي", "grup pertahanan udara", "वायु रक्षा समूह", "hava savunma grubu"),
    )
    private val fireModes = mapOf(
        FireMode.DIRECT to v("direct fire", "прямой огонь", "fuego directo", "fogo direto", "نيران مباشرة", "tembakan langsung", "प्रत्यक्ष आग", "doğrudan ateş"),
        FireMode.INDIRECT to v("indirect fire", "навесной огонь", "fuego indirecto", "fogo indireto", "نيران غير مباشرة", "tembakan tidak langsung", "अप्रत्यक्ष आग", "dolaylı ateş"),
        FireMode.AIR_TO_GROUND to v("air-to-ground", "удар по наземным целям", "aire-tierra", "ar-solo", "جو-أرض", "udara-ke-darat", "हवा से ज़मीन", "hava-yer"),
        FireMode.AIR_INTERCEPT to v("air interception", "воздушный перехват", "intercepción aérea", "interceptação aérea", "اعتراض جوي", "intersepsi udara", "वायु अवरोधन", "hava önleme"),
        FireMode.AIR_DEFENSE to v("air defense", "противовоздушная оборона", "defensa aérea", "defesa aérea", "دفاع جوي", "pertahanan udara", "वायु रक्षा", "hava savunması"),
    )
    private val enemyIntel = EnemyArchetype.entries.associateWith { v("enemy profile identified: ${it.name.lowercase()}", it.intel, "perfil enemigo: ${it.name.lowercase()}", "perfil inimigo: ${it.name.lowercase()}", "تم تحديد نمط العدو", "profil musuh teridentifikasi", "शत्रु स्वरूप पहचाना गया", "düşman profili belirlendi") }
    private val difficultyNames = mapOf(
        Difficulty.SCOUTED to v("Scouted", "Разведанная", "Reconocida", "Reconhecida", "مستطلعة", "Terintai", "टोही की गई", "Keşfedilmiş"),
        Difficulty.STANDARD to v("Standard", "Обычная", "Normal", "Normal", "عادية", "Standar", "सामान्य", "Standart"),
        Difficulty.RISKY to v("Risky", "Рискованная", "Arriesgada", "Arriscada", "خطرة", "Berisiko", "जोखिमपूर्ण", "Riskli"),
    )
    private val intelLevels = mapOf(
        Difficulty.SCOUTED to v("exact", "точная", "exacta", "exata", "دقيقة", "akurat", "सटीक", "kesin"),
        Difficulty.STANDARD to v("partial", "частичная", "parcial", "parcial", "جزئية", "sebagian", "आंशिक", "kısmi"),
        Difficulty.RISKY to v("limited", "ограниченная", "limitada", "limitada", "محدودة", "terbatas", "सीमित", "sınırlı"),
    )
    private val battlefields = mapOf(
        "Карпатский перевал" to v("Carpathian Pass", "Карпатский перевал", "Paso de los Cárpatos", "Passo dos Cárpatos", "ممر الكاربات", "Celah Karpatia", "कार्पेथियन दर्रा", "Karpat Geçidi"),
        "Дунайская долина" to v("Danube Valley", "Дунайская долина", "Valle del Danubio", "Vale do Danúbio", "وادي الدانوب", "Lembah Donau", "डेन्यूब घाटी", "Tuna Vadisi"),
        "Побережье Адриатики" to v("Adriatic Coast", "Побережье Адриатики", "Costa Adriática", "Costa Adriática", "ساحل الأدرياتيكي", "Pesisir Adriatik", "एड्रियाटिक तट", "Adriyatik Kıyısı"),
        "Патагонийское плато" to v("Patagonian Plateau", "Патагонийское плато", "Meseta Patagónica", "Planalto Patagônico", "هضبة باتاغونيا", "Dataran Tinggi Patagonia", "पैटागोनियन पठार", "Patagonya Platosu"),
        "Сахарский коридор" to v("Sahara Corridor", "Сахарский коридор", "Corredor del Sáhara", "Corredor do Saara", "ممر الصحراء", "Koridor Sahara", "सहारा गलियारा", "Sahra Koridoru"),
        "Алтайский рубеж" to v("Altai Frontier", "Алтайский рубеж", "Frontera de Altái", "Fronteira de Altai", "جبهة ألتاي", "Garis Altai", "अल्ताई सीमा", "Altay Hattı"),
        "Полесский рубеж" to v("Polesia Frontier", "Полесский рубеж", "Frontera de Polesia", "Fronteira da Polésia", "جبهة بوليسيا", "Garis Polesia", "पोलेसिया सीमा", "Polesya Hattı"),
        "Северная тундра" to v("Northern Tundra", "Северная тундра", "Tundra Septentrional", "Tundra do Norte", "التندرا الشمالية", "Tundra Utara", "उत्तरी टुंड्रा", "Kuzey Tundrası"),
        "Гобийская котловина" to v("Gobi Basin", "Гобийская котловина", "Cuenca del Gobi", "Bacia de Gobi", "حوض غوبي", "Cekungan Gobi", "गोबी बेसिन", "Gobi Havzası"),
        "Дельта Нила" to v("Nile Delta", "Дельта Нила", "Delta del Nilo", "Delta do Nilo", "دلتا النيل", "Delta Nil", "नील डेल्टा", "Nil Deltası"),
        "Анатолийское плато" to v("Anatolian Plateau", "Анатолийское плато", "Meseta de Anatolia", "Planalto da Anatólia", "هضبة الأناضول", "Dataran Tinggi Anatolia", "अनातोलियाई पठार", "Anadolu Platosu"),
        "Рейнская равнина" to v("Rhine Plain", "Рейнская равнина", "Llanura del Rin", "Planície do Reno", "سهل الراين", "Dataran Rhein", "राइन मैदान", "Ren Ovası"),
        "Предгорья Атласа" to v("Atlas Foothills", "Предгорья Атласа", "Estribaciones del Atlas", "Contrafortes do Atlas", "سفوح الأطلس", "Kaki Pegunungan Atlas", "एटलस तलहटी", "Atlas Etekleri"),
        "Амазонская низменность" to v("Amazon Lowlands", "Амазонская низменность", "Llanura Amazónica", "Planície Amazônica", "أراضي الأمازون المنخفضة", "Dataran Rendah Amazon", "अमेज़न तराई", "Amazon Ovası"),
        "Великая рифтовая долина" to v("Great Rift Valley", "Великая рифтовая долина", "Gran Valle del Rift", "Grande Vale do Rift", "الوادي المتصدع الكبير", "Great Rift Valley", "ग्रेट रिफ्ट घाटी", "Büyük Rift Vadisi"),
        "Дельта Меконга" to v("Mekong Delta", "Дельта Меконга", "Delta del Mekong", "Delta do Mekong", "دلتا ميكونغ", "Delta Mekong", "मेकांग डेल्टा", "Mekong Deltası"),
        "Деканское плато" to v("Deccan Plateau", "Деканское плато", "Meseta del Decán", "Planalto do Decão", "هضبة الدكن", "Dataran Tinggi Dekkan", "दक्कन पठार", "Dekan Platosu"),
        "Андский перевал" to v("Andean Pass", "Андский перевал", "Paso Andino", "Passo Andino", "ممر الأنديز", "Celah Andes", "एंडीज़ दर्रा", "And Geçidi"),
        "Аравийское побережье" to v("Arabian Coast", "Аравийское побережье", "Costa Arábiga", "Costa Arábica", "الساحل العربي", "Pesisir Arab", "अरब तट", "Arabistan Kıyısı"),
        "Великие равнины" to v("Great Plains", "Великие равнины", "Grandes Llanuras", "Grandes Planícies", "السهول الكبرى", "Dataran Besar", "महान मैदान", "Büyük Ovalar"),
        "Кавказский хребет" to v("Caucasus Ridge", "Кавказский хребет", "Cordillera del Cáucaso", "Cordilheira do Cáucaso", "سلسلة القوقاز", "Pegunungan Kaukasus", "काकेशस पर्वतमाला", "Kafkas Sırtı"),
        "Балтийские болота" to v("Baltic Marshes", "Балтийские болота", "Pantanos Bálticos", "Pântanos Bálticos", "مستنقعات البلطيق", "Rawa Baltik", "बाल्टिक दलदल", "Baltık Bataklıkları"),
        "Австралийский аутбэк" to v("Australian Outback", "Австралийский аутбэк", "Interior Australiano", "Interior Australiano", "المناطق النائية الأسترالية", "Pedalaman Australia", "ऑस्ट्रेलियाई आउटबैक", "Avustralya İçleri"),
        "Камчатское побережье" to v("Kamchatka Coast", "Камчатское побережье", "Costa de Kamchatka", "Costa de Kamchatka", "ساحل كامتشاتكا", "Pesisir Kamchatka", "कामचटका तट", "Kamçatka Kıyısı"),
    )
    private val biomes = mapOf(
        "горы" to v("mountains", "горы", "montañas", "montanhas", "جبال", "pegunungan", "पहाड़", "dağlar"),
        "речная долина" to v("river valley", "речная долина", "valle fluvial", "vale fluvial", "وادي نهري", "lembah sungai", "नदी घाटी", "nehir vadisi"),
        "побережье" to v("coast", "побережье", "costa", "costa", "ساحل", "pesisir", "तट", "kıyı"),
        "холмистая местность" to v("hills", "холмистая местность", "colinas", "colinas", "تلال", "perbukitan", "पहाड़ियाँ", "tepeler"),
        "пустыня" to v("desert", "пустыня", "desierto", "deserto", "صحراء", "gurun", "रेगिस्तान", "çöl"),
        "степь" to v("steppe", "степь", "estepa", "estepe", "سهوب", "stepa", "मैदान", "bozkır"),
        "лес" to v("forest", "лес", "bosque", "floresta", "غابة", "hutan", "जंगल", "orman"),
        "тундра" to v("tundra", "тундра", "tundra", "tundra", "تندرا", "tundra", "टुंड्रा", "tundra"),
        "равнина" to v("plain", "равнина", "llanura", "planície", "سهل", "dataran", "मैदान", "ova"),
        "джунгли" to v("jungle", "джунгли", "selva", "selva", "أدغال", "hutan hujan", "जंगल", "orman"),
        "болота" to v("marshes", "болота", "pantanos", "pântanos", "مستنقعات", "rawa", "दलदल", "bataklık"),
    )
}
