ALTER TABLE players
    DROP CONSTRAINT IF EXISTS players_credits_check;

CREATE TABLE star_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_telegram_id BIGINT NOT NULL REFERENCES players(telegram_id),
    pack_id VARCHAR(32) NOT NULL,
    credits INTEGER NOT NULL CHECK (credits > 0),
    price_stars INTEGER NOT NULL CHECK (price_stars > 0),
    currency VARCHAR(8) NOT NULL CHECK (currency = 'XTR'),
    invoice_payload VARCHAR(256) NOT NULL,
    telegram_payment_charge_id VARCHAR(255) NOT NULL UNIQUE,
    provider_payment_charge_id VARCHAR(255),
    ledger_reference_id UUID NOT NULL UNIQUE,
    refunded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX star_payments_player_created_idx
    ON star_payments(player_telegram_id, created_at DESC);

CREATE TABLE star_payment_support_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_telegram_id BIGINT NOT NULL REFERENCES players(telegram_id),
    payment_id BIGINT NOT NULL REFERENCES star_payments(id),
    reason TEXT NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('pending', 'info_requested', 'refunding', 'refunded', 'rejected')),
    admin_message TEXT,
    player_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX star_payment_support_one_open_idx
    ON star_payment_support_requests(payment_id)
    WHERE status IN ('pending', 'info_requested', 'refunding');

CREATE INDEX star_payment_support_status_created_idx
    ON star_payment_support_requests(status, created_at);
