CREATE TABLE players (
    telegram_id BIGINT PRIMARY KEY,
    first_name VARCHAR(128) NOT NULL,
    alliance_code VARCHAR(8),
    commander_level INTEGER NOT NULL DEFAULT 1 CHECK (commander_level BETWEEN 1 AND 50),
    xp BIGINT NOT NULL DEFAULT 0 CHECK (xp >= 0),
    credits BIGINT NOT NULL DEFAULT 500 CHECK (credits >= 0),
    materials BIGINT NOT NULL DEFAULT 100 CHECK (materials >= 0),
    combat_orders INTEGER NOT NULL DEFAULT 5 CHECK (combat_orders BETWEEN 0 AND 6),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE telegram_updates (
    update_id BIGINT PRIMARY KEY,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE battles (
    id UUID PRIMARY KEY,
    player_telegram_id BIGINT NOT NULL REFERENCES players(telegram_id),
    victory BOOLEAN NOT NULL,
    player_power INTEGER NOT NULL,
    enemy_power INTEGER NOT NULL,
    xp_reward INTEGER NOT NULL,
    credits_reward INTEGER NOT NULL,
    materials_reward INTEGER NOT NULL,
    seed_hash CHAR(64) NOT NULL,
    engine_version INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE campaign_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_key VARCHAR(16) NOT NULL,
    player_telegram_id BIGINT NOT NULL REFERENCES players(telegram_id),
    alliance_code VARCHAR(8) NOT NULL,
    credits INTEGER NOT NULL CHECK (credits > 0),
    power INTEGER NOT NULL CHECK (power > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX campaign_contributions_week_alliance_idx
    ON campaign_contributions(week_key, alliance_code);

CREATE TABLE wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_telegram_id BIGINT NOT NULL REFERENCES players(telegram_id),
    resource_type VARCHAR(32) NOT NULL,
    delta BIGINT NOT NULL,
    reason VARCHAR(64) NOT NULL,
    reference_id UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX wallet_transactions_player_created_idx
    ON wallet_transactions(player_telegram_id, created_at DESC);
