CREATE TABLE analytics_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_telegram_id BIGINT NOT NULL UNIQUE REFERENCES players(telegram_id) ON DELETE CASCADE,
    is_internal BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO analytics_players(player_telegram_id)
SELECT telegram_id
  FROM players;

CREATE TABLE player_journey_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analytics_player_id BIGINT NOT NULL REFERENCES analytics_players(id) ON DELETE CASCADE,
    session_id UUID NOT NULL,
    telegram_update_id BIGINT NOT NULL,
    event_sequence SMALLINT NOT NULL CHECK (event_sequence >= 0),
    event_name VARCHAR(64) NOT NULL,
    schema_version SMALLINT NOT NULL DEFAULT 1 CHECK (schema_version > 0),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_internal BOOLEAN NOT NULL,
    registration_source VARCHAR(16) NOT NULL,
    registration_referral VARCHAR(64),
    locale VARCHAR(8) NOT NULL,
    country_code VARCHAR(8),
    surface VARCHAR(32),
    result VARCHAR(32),
    reason VARCHAR(64),
    variant VARCHAR(32),
    reference_id VARCHAR(64),
    battle_id UUID,
    offer_version BIGINT,
    offer_slot SMALLINT,
    preset_no SMALLINT,
    used_cp INTEGER,
    entry_id VARCHAR(32),
    objective_id VARCHAR(32),
    tactic VARCHAR(32),
    unit_code VARCHAR(32),
    quantity INTEGER,
    CONSTRAINT player_journey_events_update_sequence_uk UNIQUE (telegram_update_id, event_sequence)
);

CREATE INDEX player_journey_events_player_time_idx
    ON player_journey_events(analytics_player_id, occurred_at DESC, id DESC);

CREATE INDEX player_journey_events_external_event_time_idx
    ON player_journey_events(event_name, occurred_at DESC)
    WHERE NOT is_internal;

CREATE INDEX player_journey_events_external_session_idx
    ON player_journey_events(session_id, occurred_at, id)
    WHERE NOT is_internal;

COMMENT ON TABLE player_journey_events IS
    'Versioned server-side product events. Coverage begins with V20; historical funnel steps are intentionally not inferred.';

COMMENT ON COLUMN player_journey_events.is_internal IS
    'Snapshot used to exclude confirmed owner/test accounts from product aggregates while retaining a separately filterable audit trail.';
