CREATE TABLE technical_operation_attempts (
    attempt_id UUID PRIMARY KEY,
    operation VARCHAR(16) NOT NULL,
    mode VARCHAR(16) NOT NULL,
    session_id UUID,
    resource_id UUID,
    engine_version SMALLINT,
    experiment_variant VARCHAR(32),
    is_internal BOOLEAN NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_stage VARCHAR(32),
    last_stage_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    outcome VARCHAR(16),
    failure_class VARCHAR(32),
    cache_status VARCHAR(16)
);

CREATE TABLE technical_operation_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id UUID NOT NULL REFERENCES technical_operation_attempts(attempt_id) ON DELETE CASCADE,
    stage VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_ms BIGINT NOT NULL CHECK (duration_ms >= 0),
    result VARCHAR(16) NOT NULL,
    failure_class VARCHAR(32),
    cache_status VARCHAR(16) NOT NULL,
    CONSTRAINT technical_operation_stages_attempt_stage_uk UNIQUE (attempt_id, stage)
);

CREATE INDEX technical_operation_attempts_incomplete_idx
    ON technical_operation_attempts(started_at)
    WHERE completed_at IS NULL;

CREATE INDEX technical_operation_attempts_session_time_idx
    ON technical_operation_attempts(session_id, started_at DESC)
    WHERE session_id IS NOT NULL;

CREATE INDEX technical_operation_stages_stage_time_idx
    ON technical_operation_stages(stage, occurred_at DESC);

COMMENT ON TABLE technical_operation_attempts IS
    'Durable battle and replay technical attempts. Rows without completed_at are observable unknown outcomes until restart/timeout reconciliation.';

COMMENT ON COLUMN technical_operation_attempts.resource_id IS
    'Battle or weekly matchup identifier retained only in PostgreSQL; never exported as a metric label.';
