CREATE TABLE campaign_weeks (
    week_key VARCHAR(16) PRIMARY KEY,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED')),
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE campaign_matchups (
    id UUID PRIMARY KEY,
    week_key VARCHAR(16) NOT NULL REFERENCES campaign_weeks(week_key),
    pair_index INTEGER NOT NULL CHECK (pair_index >= 0),
    battlefield VARCHAR(128) NOT NULL,
    alliance_a VARCHAR(8) NOT NULL,
    alliance_b VARCHAR(8) NOT NULL,
    contribution_a BIGINT NOT NULL DEFAULT 0 CHECK (contribution_a >= 0),
    contribution_b BIGINT NOT NULL DEFAULT 0 CHECK (contribution_b >= 0),
    contributors_a INTEGER NOT NULL DEFAULT 0 CHECK (contributors_a >= 0),
    contributors_b INTEGER NOT NULL DEFAULT 0 CHECK (contributors_b >= 0),
    npc_bonus_a INTEGER NOT NULL DEFAULT 0 CHECK (npc_bonus_a >= 0),
    npc_bonus_b INTEGER NOT NULL DEFAULT 0 CHECK (npc_bonus_b >= 0),
    score_a BIGINT CHECK (score_a >= 0),
    score_b BIGINT CHECK (score_b >= 0),
    winner_code VARCHAR(8),
    battle_seed BIGINT,
    seed_hash CHAR(64),
    engine_version INTEGER,
    events_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT campaign_matchups_distinct_alliances CHECK (alliance_a <> alliance_b),
    CONSTRAINT campaign_matchups_week_pair_unique UNIQUE (week_key, pair_index)
);

CREATE INDEX campaign_matchups_week_alliances_idx
    ON campaign_matchups(week_key, alliance_a, alliance_b);

CREATE TABLE campaign_rewards (
    id UUID PRIMARY KEY,
    week_key VARCHAR(16) NOT NULL REFERENCES campaign_weeks(week_key),
    matchup_id UUID NOT NULL REFERENCES campaign_matchups(id),
    player_telegram_id BIGINT NOT NULL REFERENCES players(telegram_id),
    alliance_code VARCHAR(8) NOT NULL,
    victory BOOLEAN NOT NULL,
    contributed_power BIGINT NOT NULL CHECK (contributed_power > 0),
    xp_reward INTEGER NOT NULL CHECK (xp_reward >= 0),
    credits_reward INTEGER NOT NULL CHECK (credits_reward >= 0),
    research_reward INTEGER NOT NULL CHECK (research_reward >= 0),
    materials_reward INTEGER NOT NULL CHECK (materials_reward >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT campaign_rewards_week_player_unique UNIQUE (week_key, player_telegram_id)
);

CREATE TABLE campaign_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_key VARCHAR(16) NOT NULL REFERENCES campaign_weeks(week_key),
    player_telegram_id BIGINT NOT NULL REFERENCES players(telegram_id),
    message TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    last_error VARCHAR(256),
    sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT campaign_notifications_week_player_unique UNIQUE (week_key, player_telegram_id)
);

CREATE INDEX campaign_notifications_pending_idx
    ON campaign_notifications(sent_at, created_at)
    WHERE sent_at IS NULL;
